---
services:
    redis-staging:
        image: redis:8
        volumes:
            - ./data:/data
        user: "1000:1000"
        ports:
          - "6380:6379"

    dash-staging:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
           - redis-staging
        image: wjallen/demo-dashboard:0.1.0
        user: "1000:1000"
        ports:
          - 8051:8050
        command:
          "python3 app.py"